# Generated by Django 6.0.6 on 2026-09-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_category_alter_expense_date_alter_income_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryType',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], help_text='Decides wether a category is either for expense or income', max_length=7, null=True),
        ),
    ]
