# Generated by Django 6.0.6 on 2026-10-07 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_category_categorytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the payment method')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryType',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], help_text='Decides whether a category is for expense or income', max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='MethodIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.income')),
                ('paymentMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='MethodExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expense')),
                ('paymentMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.paymentmethod')),
            ],
        ),
    ]
